# Generated by Django 4.2.5 on 2023-09-23 08:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_category_subcategory_product_subcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
